language: php

sudo: false

php:
    - 5.5.9
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install --prefer-dist
